### ISSUE TITLE
Can't find the mounted volume

### ISSUE THREAD

**Issue by CaptBlue** [jsknnr/enshrouded-server#103]
Hi, its very likely that I'm being dumb, I am new to using docker after all. But I can not find the mounted volume. I'm running the container via compose on Ubuntu 22.04.5 LTS.  I used the provided compose.yaml and the server has been running fine since, bringing joy to some friends and myself. However, I wanted to see if I can mess with some server configs and also want to backup the savefile. And I can not found the volume. I left the compose file as is and only changed server name, password and player slots.

`cd home/steam`

gives me the output
`-bash: cd: /home/steam: No such file or directory`

I can also not find the directory through SFTP (WinSCP) as root. What am I missing? I have not changed the volumes and path in the compose file.

Just in case, I drop my compose.yaml in here, only censoring name and password.

```
version: '3'
services:
  enshrouded:
    image: sknnr/enshrouded-dedicated-server:latest
    ports:
      - "15636:15636/udp"
      - "15637:15637/udp"
    environment:
      - SERVER_NAME=*censored*
      - SERVER_PASSWORD=*censored*
      - GAME_PORT=15636
      - QUERY_PORT=15637
      - SERVER_SLOTS=6
      - SERVER_IP=0.0.0.0
    volumes:
      - enshrouded-persistent-data:/home/steam/enshrouded/savegame

volumes:
  enshrouded-persistent-data:
```

Thanks in advance, otherweise this container runs fine and is easy to set up 💯
