### ISSUE TITLE
Server crashing on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by LvInSaNevL** [jsknnr/enshrouded-server#50]
Hey guys I am trying to set up a dedicated server on my Linux (running Ubuntu 22.04) host but the docker container wont stay up for more than ~1 minute before shutting down. I don't see any logs and it doesn't actually save any files to my directory. 

Here is my `docker-compose.yaml`

```yml
services:
  enshrouded:
    image: sknnr/enshrouded-dedicated-server
    container_name: enshrouded
    ports:
      - "15636:15636/udp"
      - "15637:15637/udp"
    environment:
      - SERVER_NAME: "My Server"
      - SERVER_PASSWORD: "MyPassword"
      - GAME_PORT: 15636
      - QUERY_PORT: 15637
      - SERVER_SLOTS: 4
      - SERVER_IP: 127.0.0.1
    volumes:
      - ./save_data:/home/steam/enshrouded/savegame
```

I changed the sever IP from the `0.0.0.0` that was in the README to `127.0.0.1` based on the advice from [this issue](https://github.com/jsknnr/enshrouded-server/issues/16)

I also noticed that when I got connected to the server `enshrouded_server_example.json` was not updated with my information so I manually updated that and restarted the container but no luck there either. 

Maybe I am missing something with the `docker-compose`?  

Edit: I messed up my port config so I corrected that

**Comment by TrueOsiris** [comment]
My 2 cents to get the container running, using an exposed volume, like you (instead of letting docker handle the volume).

- I had to create the user and chown the volume location with that user:group.
  ``` bash 
  groupadd enshrouded -g 10000
  useradd enshrouded -u 10000 -g 10000 -m -s /bin/bash
  chown -R enshrouded:enshrouded /path/on/host/enshrouded
  ```
  And then in the compose, the source needs to reflect this folder, obviously.
  ``` yaml
  services:
    enshrouded:
      image: sknnr/enshrouded-dedicated-server:latest
      ports:
        - "15636:15636/udp"
        - "15637:15637/udp"
      environment:
        - SERVER_NAME=TestEnshrouded
        - SERVER_PASSWORD=testing
        - GAME_PORT=15636
        - QUERY_PORT=15637
        - SERVER_SLOTS=16
        - SERVER_IP=0.0.0.0
      volumes:
        - type: bind
          source: /path/on/host/enshrouded
          target: /home/steam/enshrouded/savegame
          bind:
            create_host_path: true
      restart: unless-stopped
      network_mode: bridge
  ```
- I think you reversed the external:internal port, unless you somehow changed the internal port in the config file.<br>
- If you use different in-out ports for dockerized steam-dedicated servers, they work, if you connect directly. But most of the times, they will not properly propagate to the serverlist.

**Comment by LvInSaNevL** [comment]
@TrueOsiris Okay, do I need to make the `enshrouded` user on the server? 

Also, I just messed up my docker config when I was copying it over, that's my bad it should be this

```
    ports:
      - "15636:15636/udp"
      - "15637:15637/udp"
```

I'll update it in my original question too.

**Comment by TrueOsiris** [comment]
The user doesn't need to be named 'enshrouded'. It can be anything.
You need to create (or have) a user and group, both with id 10.000.

You ONLY need this because you use an exposed host volume (like me): **./save_data**:/home/steam/enshrouded/savegame
I used an absolute path in the docker-compose.yaml: `source: /path/on/host/enshrouded`
U use a relative path, based on the folder you have your docker-compose.yml in: `./save_data`
Both are exposed volumes. 

The alternative is having docker manage the persistent volume, as the dev of this repo is doing.
```
services:
  ...
    volumes:
      - enshrouded-persistent-data:/home/steam/enshrouded/savegame

volumes:
  enshrouded-persistent-data:
```
Then the volume is also persistent, but u can only reach it through docker commands. 
Docker then will handle rights and users, making this part easier.
However, in most cases you do not want that, as you want to backup & restore files in those exposed volumes on an OS level.

The fact that the container access its volumes with user & group 10000 is embedded in the image and might even be embedded in the dedicated server software, imho.
