### ISSUE TITLE
Enhancement Request: Add Custom Annotation Option for Service

### ISSUE THREAD

**Issue by Enorshionari** [jsknnr/enshrouded-server#54]
**Issue:**
Currently, the service template in the helm chart lacks the ability to set custom annotations for services, which can be particularly beneficial for users utilizing metalLB or DigitalOcean LoadBalancers.

**Suggestion:**
I propose adding an option to set custom annotations for services. This enhancement would allow users to define annotations tailored to their specific needs, providing greater flexibility and compatibility with various load balancing solutions.
    
```
apiVersion: v1
kind: Service
metadata:
  name: "enshrouded-dedicated-server-service"
  labels:
    app: "enshrouded-dedicated-server"
    chart: "enshrouded-dedicated-server-1.0.0"
    release: "enshrouded-test"
    heritage: "Helm"
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.88.200 # example MetalLB annotation
    custom.annotation/key: "value"  # custom annotation example
spec:
  type: LoadBalancer
  ports:
  - name: game-port
    port: 2222
    targetPort: game-port
    protocol: UDP
  - name: query-port
    port: 1111
    targetPort: query-port
    protocol: UDP
  selector:
    app: "enshrouded-dedicated-server"
```

**Benefits:**

Enhanced compatibility with metalLB and DigitalOcean LoadBalancers.
Empowers users to define custom annotations tailored to their specific requirements.
Provides greater flexibility in configuring and optimizing load balancing solutions.
