### ISSUE TITLE
Fatal Error: Steamcmd needs 250MB of free disk space to update.

### ISSUE THREAD

**Issue by Ginie66** [jsknnr/enshrouded-server#57]
After the dismal performance of the wine build, I decided to try your proton build server.

However, I keep coming up with the following error. After changing all the folders, perms are recommended on the internet. There are no issues with space; I have 100GB on the server. 

<img width="390" alt="image" src="https://github.com/jsknnr/enshrouded-server/assets/14190873/b5d540cf-7ea9-4758-8a78-8bf6d5402caa">

```
02/10/2024 10:11:26 AM [----] Update complete, launching Steamcmd...
02/10/2024 10:11:26 AM tid(24) burning pthread_key_t == 0 so we never use it
02/10/2024 10:11:26 AM Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
02/10/2024 10:11:26 AM Logging directory: '/home/steam/Steam/logs'
02/10/2024 10:11:26 AM [----] Verifying installation...
02/10/2024 10:11:26 AM [----] !!! Fatal Error: Steamcmd needs 250MB of free disk space to update.
02/10/2024 10:11:26 AM 2024-02-09 23:11:26,818 ERROR: steamcmd was unable to successfully initialize and update Enshrouded
02/10/2024 10:13:31 AM 2024-02-09 23:13:31,100 INFO: Updating Enshrouded Dedicated Server
02/10/2024 10:13:31 AM tid(12) burning pthread_key_t == 0 so we never use it
02/10/2024 10:13:31 AM Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
02/10/2024 10:13:31 AM Logging directory: '/home/steam/Steam/logs'
02/10/2024 10:13:31 AM [----] Verifying installation...
02/10/2024 10:13:31 AM [----] !!! Fatal Error: Steamcmd needs 250MB of free disk space to update.
02/10/2024 10:13:31 AM 2024-02-09 23:13:31,292 ERROR: steamcmd was unable to successfully initialize and update Enshrouded
```

Running Ubuntu with docker 25.0.0 

```
services:
  enshrouded:
    hostname: enshrouded
    container_name: enshrouded
    image: sknnr/enshrouded-dedicated-server:proton-latest
    ports:
      - "15636:15636/udp"
      - "15637:15637/udp"
    environment:
      - SERVER_NAME=Friday Night Light (FLN)
      - SERVER_PASSWORD=theyboys123
      - GAME_PORT=15636
      - QUERY_PORT=15637
      - SERVER_SLOTS=16
      - SERVER_IP=0.0.0.0
    volumes:
      - /home/game-admin/games/enshrouded/savedgame:/home/steam/enshrouded/savegame
```
