### ISSUE TITLE
how to import locally saved world

### ISSUE THREAD

**Issue by effektarium** [jsknnr/enshrouded-server#59]
Hi there! :) 
Actually no issue but i cant find the directory of my container. 
I installed the server on my synology nas via docker and i really have no idea what im doing, but the server is running.
but i cant find the docker dir 
Can anybody help me here? :)

**Comment by seb-giroux** [comment]
I'd love to have this answer as well.

**Comment by seb-giroux** [comment]
Allright so I succesfully did it in two steps:
1.  Add a volume between a folder (You can create one for Enshrouded specifically) and `/home/steam/enshrouded/savegame`
![image](https://github.com/jsknnr/enshrouded-server/assets/8069361/900ea8ad-4b62-4bc1-95d3-14a4f6c09b39)

2. Use the File Station app to copy your save game to this new folder:
![image](https://github.com/jsknnr/enshrouded-server/assets/8069361/ff836379-3801-4762-8ac6-f1abe125f412)

**Comment by effektarium** [comment]
> Allright so I succesfully did it in two steps:

Oh, great, thx a lot!

**Comment by TFidk** [comment]
Hello. I'm in the same situation. I set up the server on a Synology NAS yesterday and the server started. But where does it save the server game files? The folder I mounted only contains compose.yaml. In which folder does the server save all the other files? I also created a separate subfolder “save” where I wanted to copy the save games.

![IMG_1447](https://github.com/user-attachments/assets/41442276-ad9a-4b70-9898-ff673e099d30)

**Comment by riuson** [comment]
@TFidk,
The docker-compose file in Readme uses persistent storage on **volume**.
To save data on disk of host system, you can bind it to host's path.
Alternatively, you can upload your saves into volume.

**Comment by TFidk** [comment]
@riuson: Hello and thanks for your fast reply. I'm still very new to the Docker segment. Where can I find this folder? I can't find it in the Synology DS file.

**Comment by riuson** [comment]
Down container (not stop or restart).
Change compose to
```yaml
version: '3'
services:
  enshrouded:
    image: sknnr/enshrouded-dedicated-server:latest
    ports:
      - "15636:15636/udp"
      - "15637:15637/udp"
    environment:
      - SERVER_NAME=Enshrouded Containerized
      - SERVER_PASSWORD=PleaseChangeMe
      - GAME_PORT=15636
      - QUERY_PORT=15637
      - SERVER_SLOTS=16
      - SERVER_IP=0.0.0.0
    volumes:
      - ./data:/home/steam/enshrouded/savegame
```
Make directory near it:
```bash
mkdir ./data
chown 10000:10000 ./data
```
And up again.
